catalog:
  '@types/node': ^26.4.0
  '@types/pngjs': ^6.0.5
  '@vitejs/plugin-vue': ^6.0.8
  '@vueuse/core': ^14.4.0
  '@vueuse/router': ^14.4.0
  immer: ^11.1.18
  ol: ^10.10.0
  pinia: ^4.0.3
  pngjs: ^7.0.0
  typescript: ^6.0.3
  unocss: ^66.9.2
  vite: ^8.2.2
  vitest: ^4.1.11
  vue: ^3.5.42
  vue-router: ^5.3.1
  vue-tsc: ^3.3.11
  zod: ^4.5.4
