import { z } from 'zod'

const finiteNumber = z.number().finite()
const nullableString = z.string().nullable()

export const gameCoordinateSchema = z.object({
  x: finiteNumber,
  y: finiteNumber,
  z: finiteNumber,
})

const officialCoordinateSchema = z.object({
  rawX: finiteNumber,
  rawY: finiteNumber,
  mapX: finiteNumber,
  mapY: finiteNumber,
})

const pointBaseShape = {
  id: z.string().min(1),
  typeId: z.string().min(1),
  typeName: z.string().min(1),
  iconUrl: z.string(),
  stateId: z.number().int(),
  countryId: z.number().int().nullable(),
  layeredMapId: nullableString,
  levelId: nullableString,
  coordinate: officialCoordinateSchema,
  gameCoordinate: gameCoordinateSchema.nullable(),
  quality: z.enum(['official-provisional', 'manual-verified', 'example']),
}

export const mapDatasetSchema = z.object({
  version: z.literal(3),
  source: z.object({
    generatedAt: z.string(),
    wikiFetchedAt: z.string(),
    mapFetchedAt: z.string(),
    mapResourceHash: z.string().min(1),
    tileWidth: z.number().positive(),
    coordinateRate: z.number().positive(),
    coordinateScaleBase: z.number().positive(),
    sourceUrls: z.object({
      echoCatalogue: z.string(),
      sonataCatalogue: z.string(),
      officialMap: z.string(),
    }),
  }),
  report: z.object({
    wikiEchoCount: z.number().int().nonnegative(),
    includedEchoCount: z.number().int().positive(),
    excludedEchoCount: z.number().int().nonnegative(),
    sonataCount: z.number().int().positive(),
    exactMatchedEchoCount: z.number().int().nonnegative(),
    aliasMatchedEchoCount: z.number().int().nonnegative(),
    unmatchedEchoNames: z.array(z.string()),
    provisionalEchoLocationCount: z.number().int().nonnegative(),
    routeEligibleEchoLocationCount: z.number().int().nonnegative(),
    navigationPointCount: z.number().int().nonnegative(),
    navigationPointGroupCount: z.number().int().nonnegative(),
    bossNavigationPointCount: z.number().int().nonnegative(),
    challengeNavigationPointCount: z.number().int().nonnegative(),
    navigationIconFetchFailureCount: z.number().int().nonnegative(),
    routeEligibleNavigationPointCount: z.number().int().nonnegative(),
  }),
  sonatas: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    iconUrl: z.string(),
    sourceId: z.number().int(),
  })).min(1),
  echoes: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    iconUrl: z.string(),
    sonataIds: z.array(z.string().min(1)).min(1),
    cost: z.union([z.literal(1), z.literal(3)]),
    sourceId: z.number().int(),
  })).min(1),
  states: z.array(z.object({
    id: z.number().int(),
    name: z.string().min(1),
    tileIds: z.array(z.string()),
    tileExtent: z.object({
      minTileX: z.number().int(),
      minTileY: z.number().int(),
      maxTileX: z.number().int(),
      maxTileY: z.number().int(),
      extent: z.tuple([finiteNumber, finiteNumber, finiteNumber, finiteNumber]),
    }),
    layeredMaps: z.array(z.object({
      id: z.string(),
      name: z.string(),
      floors: z.array(z.object({
        id: z.string(),
        name: z.string(),
        layeredMapId: z.string(),
        tiles: z.array(z.string()),
      })),
    })),
  })).min(1),
  regionLabels: z.array(z.object({
    id: z.string(),
    name: z.string(),
    stateId: z.number().int(),
    countryId: z.number().int(),
    level: z.number().int(),
    coordinate: officialCoordinateSchema,
  })),
  echoLocations: z.array(z.object({
    ...pointBaseShape,
    echoId: z.string().min(1),
  })),
  navigationPointGroups: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    iconUrl: z.string(),
    iconHash: z.string().length(64).nullable(),
    typeIds: z.array(z.string().min(1)).min(1),
    typeNames: z.array(z.string().min(1)).min(1),
    modes: z.array(z.enum(['fast-travel', 'local-transit', 'entrance', 'landmark', 'unknown'])).min(1),
    kinds: z.array(z.enum([
      'nexus',
      'beacon',
      'tacet-field',
      'training-ground',
      'hologram',
      'boss',
      'domain',
      'endgame',
      'challenge',
      'service',
      'local-transit',
      'entrance',
      'landmark',
      'unknown',
    ])).min(1),
  })),
  navigationPoints: z.array(z.object({
    ...pointBaseShape,
    groupId: z.string().min(1),
    catalogCategoryId: z.string().min(1),
    catalogCategoryName: z.string().min(1),
    mode: z.enum(['fast-travel', 'local-transit', 'entrance', 'landmark', 'unknown']),
    kind: z.enum([
      'nexus',
      'beacon',
      'tacet-field',
      'training-ground',
      'hologram',
      'boss',
      'domain',
      'endgame',
      'challenge',
      'service',
      'local-transit',
      'entrance',
      'landmark',
      'unknown',
    ]),
  })),
  connectors: z.array(z.object({
    id: z.string(),
    name: z.string(),
    stateId: z.number().int(),
    fromLevelId: z.string(),
    toLevelId: z.string(),
    from: gameCoordinateSchema,
    to: gameCoordinateSchema,
    traversalCost: z.number().nonnegative(),
    isExample: z.boolean(),
  })),
})
